[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[[language]]
name = "toml"
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "bash"
language-servers = ["bash-language-server"]
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.md"] }
auto-format = true

[language-server.dockerfile-language-server]
command = "docker-langserver"
args = ["--stdio"]

[[language]]
name = "dockerfile"
language-servers = ["dockerfile-language-server"]
formatter = { command = "dockerfmt" }
auto-format = true
file-types = [
  "Dockerfile",
  "Containerfile",
  { glob = "*.containerfile" },
  { glob = "*.dockerfile" },
]
