[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20            # set max completion results len for each group: words, snippets, unicode-input
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

[language-server.scls.environment]
SNIPPETS_PATH = "/home/dev/app/env/dev/snippets"

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[[language]]
name = "toml"
language-servers = ["scls", "taplo"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "bash"
language-servers = ["scls", "bash-language-server"]
formatter = { command = "shfmt" }
auto-format = true

[language-server.vscode-markdown-language-server]
command = "vscode-markdown-language-server"
args = ["--stdio"]

[[language]]
name = "markdown"
language-servers = ["scls", "vscode-markdown-language-server"]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.md"] }
auto-format = true

[language-server.dockerfile-language-server]
command = "docker-langserver"
args = ["--stdio"]

[[language]]
name = "dockerfile"
language-servers = ["scls", "dockerfile-language-server"]
formatter = { command = "dockerfmt" }
auto-format = true
file-types = [
  "Dockerfile",
  "Containerfile",
  { glob = "*.containerfile" },
  { glob = "*.dockerfile" },
]

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[[language]]
name = "json"
language-servers = ["scls", "vscode-json-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.json"] }
auto-format = true

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

[[language]]
name = "yaml"
language-servers = ["scls", "yaml-language-server"]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.yaml"] }
auto-format = true

[[language]]
name = "html"
language-servers = ["scls", "vscode-html-language-server"]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.html"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["scls", "vscode-css-language-server"]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.css"] }
auto-format = true

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[[language]]
name = "typescript"
file-types = ["ts", "tsx"]
language-servers = ["scls", "typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.ts"] }
auto-format = true

[[language]]
name = "javascript"
file-types = ["js", "jsx", "mjs", "cjs"]
language-servers = ["scls", "typescript-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.js"] }
auto-format = true

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/home/dev/.local/share/mise/installs/npm-typescript/latest/lib/node_modules/typescript/lib" } }

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
comment-token = "//"
# NOTE: snippets work better when scls is second lsp, not first
language-servers = ["astro-ls", "scls", "tailwindcss-ls"]
formatter = { command = "prettier", args = [
  "--stdin-filepath",
  "file.astro",
  "--plugin",
  "prettier-plugin-astro",
] }
auto-format = true

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.tailwindcss-ls.config]
tailwindCSS.experimental.configFile = "./src/assets/css/global.css"
tailwindCSS.includeLanguages = { astro = "html", typescript = "javascript", tsx = "javascript" }
tailwindCSS.emmetCompletions = true
tailwindCSS.classAttributes = ["class", "className", "class:list", "classList"]
tailwindCSS.validate = true
tailwindCSS.lint.cssConflict = "warning"
tailwindCSS.lint.invalidApply = "error"
tailwindCSS.lint.invalidScreen = "error"
tailwindCSS.lint.invalidTailwindDirective = "error"
tailwindCSS.lint.invalidVariant = "error"
tailwindCSS.lint.recommendedVariantOrder = "warning"

[[language]]
name = "kdl"
language-servers = ["scls"]
formatter = { command = "kdlfmt", args = ["format", "--stdin"] }
auto-format = true
