[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]

[[language]]
name = "toml"
language-servers = ["scls, taplo"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "bash"
language-servers = ["scls", "bash-language-server"]
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["scls"]
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.md"] }
auto-format = true

[language-server.dockerfile-language-server]
command = "docker-langserver"
args = ["--stdio"]

[[language]]
name = "dockerfile"
language-servers = ["scls", "dockerfile-language-server"]
formatter = { command = "dockerfmt" }
auto-format = true
file-types = [
  "Dockerfile",
  "Containerfile",
  { glob = "*.containerfile" },
  { glob = "*.dockerfile" },
]

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[[language]]
name = "json"
language-servers = ["scls", "vscode-json-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.json"] }
auto-format = true
